### ISSUE TITLE
Webpack 2 validation

### ISSUE THREAD

**Issue by kentcdodds** [js-dxtools/webpack-validator#101]
I just noticed [this](https://gist.github.com/sokra/27b24881210b56bbaff7#configuration)

![screen shot 2016-05-23 at 8 19 44 pm](https://cloud.githubusercontent.com/assets/1500684/15490300/f87518ac-2123-11e6-9303-5b76b9c48306.png)

Anyone know what's being planned by way of validation in webpack 2?

**Comment by bebraw** [comment]
That's a good question.

Any thoughts on this @sokra? What sort of validation are you planning for webpack 2?

**Comment by sokra** [comment]
Nothing planned yet, but it's good to do the necessary breaking changes to make it possible.

**Comment by kentcdodds** [comment]
Looking forward to the day that webpack-validator is less necessary :-)
