### ISSUE TITLE
Fails with extra section for stylus plugins

### ISSUE THREAD

**Issue by bfin** [js-dxtools/webpack-validator#104]
Per https://github.com/shama/stylus-loader#stylus-plugins, stylus plugins are added to an extra 'stylus' section in the webpack config.

```js
var rupture = require('rupture');
module: {
  loaders: [
    { test: /\.styl$/, loader: 'css-loader!stylus-loader' }
  ]
},
stylus: {
  use: [rupture()]
}
```

However, this fails validation with `webpack-validator`.

```
"stylus" is not allowed
```

**Comment by jonathanewerner** [comment]
Hi! Please have a look at https://github.com/js-dxtools/webpack-validator/blob/master/README.md#schema as it exactly explains the solution for your problem. let me know if it works for you. 👍🏻

**Comment by kentcdodds** [comment]
This would be a great opportunity for a "plugin library" @bfin, if you're interested in creating something like that. Would basically require a module that has a `peerDependency` on `webpack-validator` and exports a schema for the `stylus` property.

**Comment by bfin** [comment]
@jonathanewerner Facepalm... Imagine that -- it's addressed right there in the readme! Thanks for being nice about it...grin.

@kentcdodds It'd probably be a good learning opportunity, but putting something like that together is currently beyond my abilities. Thanks for the suggestion, though

**Comment by kentcdodds** [comment]
@bfin, well, when you feel up to it you might benefit from my video series on the subject :-) http://kcd.im/write-oss
