### ISSUE TITLE
Support custom schema with CLI

### ISSUE THREAD

**Issue by kentcdodds** [js-dxtools/webpack-validator#106]
I envision something like:

``` console
webpack-validator webpack.config.js --schema-extension ./other/my-schema.js
```

Where `./other/my-schema.js` is simply a module that exports the schema:

``` javascript
const validate = require('webpack-validator')
const Joi = require('webpack-validator').Joi
module.exports = Joi.object({
  eslint: Joi.any()
})
```

Thinking about it further, it would be nice to be able to configure all options via the CLI :+1:

**Comment by jonathanewerner** [comment]
we probably need yet another rc-file. (webpack-validatorrc.js 🙈; needs to have Js for the schemaExtension). The thought of yet another meta file pains me but I see no better solution. 😐
