### ISSUE TITLE
watch option is not allowed

### ISSUE THREAD

**Issue by andrewQwer** [js-dxtools/webpack-validator#108]
When I use `watch: true` option in my config validator says that it is not valid, but according to this documentation https://webpack.github.io/docs/cli.html#watch - it's ok to use it.

**Comment by kentcdodds** [comment]
Hi @andrewQwer,
Thanks for letting us know. Would you like to [makeapullrequest.com](http://makeapullrequest.com) to add it? You'd put it right around [here](https://github.com/js-dxtools/webpack-validator/blob/d7f0f6f34fcd462275fd66b420361e334d92a1c2/src/index.js#L47) I think. Then if you could also add a test config [here](https://github.com/js-dxtools/webpack-validator/tree/d7f0f6f34fcd462275fd66b420361e334d92a1c2/test/passing-configs) that'd be awesome. Thanks!

**Comment by andrewQwer** [comment]
Sure, I can make a PR to fix this.
