### ISSUE TITLE
support the `progress` top-level attribute

### ISSUE THREAD

**Issue by travi** [js-dxtools/webpack-validator#110]
setting `progress: false` is helpful for removing the noise that appears in the output of a CI server build since the progress percentage doesn't update in-place like it does in a true terminal. However, when i have this setting in my config, i am warned about it: `[1] "progress" is not allowed`. any reason that this isn't allowed by the validator?

**Comment by bebraw** [comment]
It's just missing from the schema. A PR could be welcome unless someone gets to it first. 👍

**Comment by nyrosmith** [comment]
I close this as it seems we have it already implemented.
Feel free to reopen if there are still issues with the "progress" prop
