### ISSUE TITLE
'npm run test' not working on windows

### ISSUE THREAD

**Issue by nyrosmith** [js-dxtools/webpack-validator#130]
Win 10 x64
node: 4.4.7.
I have also tried with node 6.3.1. (current)

It seems that mocha freezes when running the tests. All I get is

```
webpack-validator@ test E:\webpack-validator
cross-env NODE_ENV=test mocha "src/**/*.test.js"
  ......................................
```

and then it hangs forever.
I am really not sure if it is a problem in the scripts or mocha itself. Help would be really appreciated...

**Comment by kentcdodds** [comment]
Hmmm... I got it working (on my mac) without trouble. Maybe there's a specific test that has problems. Could you see if you can find the hanging test?

**Comment by nyrosmith** [comment]
Need to do binary search to detect the potential test. Let me see if I find something suspicious.

**Comment by nyrosmith** [comment]
I could tackle the problem down to [this line](https://github.com/js-dxtools/webpack-validator/blob/master/src/rules/no-root-files-node-modules-nameclash.js#L56)
Nothing after 
`const nodeModuleFolder = findNodeModules({ cwd: path_, relative: false })[0]`
executes.
The problematic test whith the problem causing config is [this one](https://github.com/js-dxtools/webpack-validator/blob/master/src/properties/resolve/index.test.js#L17)

My approach is to adjust the testConfigs to provide valid absolute paths if ENV === windows.
Any thoughts about this solution @kentcdodds @jonathanewerner ?

**Comment by kentcdodds** [comment]
I'd love to see it 👍

**Comment by nyrosmith** [comment]
After some hours of investigation I found the following possible solution.
- create valid absolute paths in our tests depending on current OS
- Fix query if it's an absolute path (#131)
- split passing & non passing configs in different folders (per OS)
- run these test webpack-configs tests for the current OS

This is a bigger change as I expected and it might have some tradeoffs, but otherwise I would not be able to contribute any longer which I really like...

I don't want to make that changes until you all are  ok with that @kentcdodds @bebraw @jonathanewerner

**Comment by bebraw** [comment]
Fine by me. If you can encapsulate the path bits somewhere, that would be great.

**Comment by kentcdodds** [comment]
:shipit: 😄

**Comment by jonathanewerner** [comment]
> Fine by me. If you can encapsulate the path bits somewhere, that would be great.

Yea, let's extract this as `test/mock/absolutePath` or something.
