### ISSUE TITLE
'absolutePath' not working for windows environments

### ISSUE THREAD

**Issue by nyrosmith** [js-dxtools/webpack-validator#131]
[This line](https://github.com/js-dxtools/webpack-validator/blob/62c70f92ac4a0e479adf20e0addde4180ae69893/src/types/absolutePath.js#L22) returns true when given 'bla'. But 'bla' is not an absolute path in Windows.

I'd suggest to use [path-is-absolute](https://www.npmjs.com/package/path-is-absolute) to solve this issue.
With this change we also need to adjust configs to give valid/invalid absolute paths.

If it is ok for you I'll provide a PR as it seems I am the only dev in this world who is using this OS on JS OSS.

Related Path issue: https://github.com/js-dxtools/webpack-validator/issues/130

**Comment by kentcdodds** [comment]
Love it. Let's do that 👍

**Comment by nyrosmith** [comment]
Regarding to [this line](https://github.com/js-dxtools/webpack-validator/blob/62c70f92ac4a0e479adf20e0addde4180ae69893/src/types/absolutePath.js#L22)
`const looksLikeAbsolutePath = /^(?!\.?\.\/).+$/.test('exists')` is true. But the [node documentation](https://nodejs.org/api/path.html#path_path_isabsolute_path) says this in not an absolute posix path. 

I am really confused now. May it be possible that we don't ask for valid absolute paths at all?
Pinging @kentcdodds @bebraw @jonathanewerner for clarification.

**Comment by jonathanewerner** [comment]
To be honest i'm not 100% positive that "foobar" would classify as an absolute POSIX path -- not sure what my intention was there -- maybe it had something to do with webpack *handling* a path like "foobar" as an absolute path? 
Anyways, lets just replace "looksLikeAbsolutePath" with your suggested library `path-is-absolute`, @nyrosmith -- problem solved, no?

I think checking for absolute paths is a big UX win as this *is* one of the major confusing parts when configuring webpack -- where to use absolute vs relative paths.
