### ISSUE TITLE
Custom validations for module.loaders[x]

### ISSUE THREAD

**Issue by IgnusG** [js-dxtools/webpack-validator#132]
_Node: v5.12.0_
_webpack-validator: 2.2.7_

It is impossible to customize these validations with schemaExtension since the concat method from Joi doesn't extend the original object in the array but rather includes a new one. (See: https://github.com/hapijs/joi/issues/978). 

This means, as far as I know, that you can either have webpack-validator's validations for a loader object or you have to write them yourself and extend them with whatever you need.

**Comment by bradleygore** [comment]
I'm having the same issue - and it just started happening. I've been using 2.2.7 for a while now, but just recently the `schemaExtension` functionality stopped working in that version.

I'm using the less-loader for webpack, and using the `Joi.object` approach as documented to tell webpack validator about the property:

```
const configSchemaExtension = Joi.object({
    lessLoader: Joi.any()
});

module.exports = webpackValidator(
    appConfig,
    {schemaExtension: configSchemaExtension}
);
```

Any idea why this suddenly started happening?
