### ISSUE TITLE
Why use Joi and not Ajv?

### ISSUE THREAD

**Issue by pksjce** [js-dxtools/webpack-validator#138]
I found that webpack itself uses [ajv](https://github.com/epoberezkin/ajv) with this [JSON schema](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json) to validate it's configs.
If that is the case, why duplicate that using Joi? Was there any specific reason?

**Comment by jonathanewerner** [comment]
This library was mainly written half a year ago. Look at the history for webpack schemas: https://github.com/webpack/webpack/commits/master/schemas
:)

**Comment by pksjce** [comment]
Ah! That was a bit naive of me. Wouldn't this project be easier to update and maintain if it too used the same schema as webpack now?

**Comment by jonathanewerner** [comment]
It probably makes sense to deprecate this project soon now that webpack core does it. :)

**Comment by pksjce** [comment]
He he. Cool. Got it!
