### ISSUE TITLE
Suggest correct properties for misspellings

### ISSUE THREAD

**Issue by jonathanglasmeyer** [js-dxtools/webpack-validator#14]
I don't think Joi does this by default. Would have to think about a way to go forward here. Maybe catch the joi error, parse if it is of the type `object.allowUnknown` and then present correct keys for the given `path`. 
Context: an joi error object for an invalid property looks like `Object{message:"\"fileName\" is not allowed",path:"fileName",type:"object.allowUnknown",context:#Object#}`. 
Something like that. :)

**Comment by kentcdodds** [comment]
I think it'd be better to see if we can get this supported in Joi. I'm sure they'd like to have this feature.

**Comment by jonathanewerner** [comment]
I opened an issue over there: https://github.com/hapijs/joi/issues/861#issuecomment-207622309

**Comment by jonathanewerner** [comment]
So i was told that the core is fat enough and this should be handled by a plugin. A plugin infrastructure is in the works; in the meantime this should be solved via manual error post-processing. Might make sense though to extract it into another package, seems quite generic. Something like `joi-spelling-hints` or sth in that vein :)

**Comment by nyrosmith** [comment]
I am looking at a solution right now

**Comment by jonathanewerner** [comment]
Hey @nyrosmith, are you still looking at this?

**Comment by nyrosmith** [comment]
ATM I really have problems finding some time for this project. If someone else has more spare time pls make it. But it is still on my List...

**Comment by jonathanewerner** [comment]
Ok, no stress. Looking forward to your input when you've got more time again. :+1:
