### ISSUE TITLE
webpack 2 syntax for preloader (`enforce: 'pre'`) return error

### ISSUE THREAD

**Issue by olivier-o** [js-dxtools/webpack-validator#142]
using the webpack 2 syntax for preloader (`enforce: 'pre'`)  ...
```
loaders: [
      {
        test: /\.jsx?$/,
        loader: 'eslint-loader?{fix: true}',
        exclude: /node_modules/,
        enforce: 'pre'
      },
```
return `"enforce" is not allowed` error message. 
Will be glad to work on a fix, if someone can point me to where this validation is happening

**Comment by hinok** [comment]
Have the same problem. In the readme is written that

```
Note that as of webpack v2 (currently in beta), configuration validation is baked in.
```

So for webpack 2, there is no reason to use `webpack-validator`? I found something in the webpack repository

- **Issue**: https://github.com/webpack/webpack/issues/2971
- **PR**: https://github.com/webpack/webpack/pull/2974

Could someone explain it clearly?

**Comment by biswassuman23** [comment]
Same issue what is the solution?

**Comment by kentcdodds** [comment]
The solution is to not use this package with Webpack 2 anymore. It's no longer necessary. Please see the notice in the README. Cheers!
