### ISSUE TITLE
resolve.modules is not allow (webpack-validator 2.3.0) (with webpack 2.1.0-beta.28) 

### ISSUE THREAD

**Issue by ApolloTang** [js-dxtools/webpack-validator#151]
I am trying to configure resolve.modules according to:

https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options

```
"resolve": {
    "modules" [1]: [
      "/Users/apollotang/Desktop/g-webpack/webpack-sandbox/05-modules/src",
      "/Users/apollotang/Desktop/g-webpack/webpack-sandbox/05-modules/node_modules"
    ]
  },
```

but validator tells me 
```
[1] "modules" is not allowed
```

I think this is a bug, b/c after disable validator, webpack works as expected. 

I am using  webpack-validator 2.3.0 with webpack 2.1.0-beta.28.

my code can be read at: 
https://github.com/ApolloTang/webpack2-setup/tree/master/05-modules

**Comment by kentcdodds** [comment]
Thanks for the report. Please see the note in the README about this package no longer officially supporting Webpack 2. Is this a problem with Webpack 1?

**Comment by ApolloTang** [comment]
i am using it with webpack 2, just read the README you mentioned; so WP2 has built in validator, so I can now uninstall this module, Thanks!
