### ISSUE TITLE
Validate webpack-dev-server specific fields

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#21]
See https://webpack.github.io/docs/webpack-dev-server.html .

**Comment by nlarche** [comment]
I'm not sure about all webpack-dev-server specific fields : 
 - from webpack-dev-server CLI doc
  - contentBase
  - quiet
  - noInfo
  - colors
  - noColors
  - compress
  - host
  - port
  - inline
  - hot
  - lazy
  - https
  - cert
  - cacert,
  - key,
  - open,
  - historyApiFallback
  
 - from api doc
  
  - proxy
  - staticOptions
  - filename
  - watchOptions
  - publicPath
  - headers
  - stats

what do you think ?

**Comment by bebraw** [comment]
It's perhaps easiest to check the [source](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js). There is type information too.

@nlarche Do you want to give it a go?

**Comment by nlarche** [comment]
why not ! I'll check the source

**Comment by bebraw** [comment]
Cool. Poke this thread if you get into trouble. The testing approach is pretty awesome once you get it. 👍

**Comment by nlarche** [comment]
ok thanks

**Comment by jonathanewerner** [comment]
:tada: welcome on board. :)

**Comment by nlarche** [comment]
Pull request #75 is ready for review
