### ISSUE TITLE
Implement strict mode?

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#35]
I wonder if having a stricter validator would be valuable. It could be useful to disallow things like loader definitions without `include`/`exclude`. And even then it could be nice to prefer `include` over `exclude` (latter gives a warning?). I have a list of rules like these in mind.

**Comment by jonathanewerner** [comment]
That sounds good. It'd have to be a set of rules that's pretty uncontroversial no? Do you have some kind of list of best practices written down somewhere?

**Comment by bebraw** [comment]
I have a list of good practices, yeah. I'll open separate issues for those so we can think about this better.

Implementing a strict mode would take this library closer to a linter but that's not a bad thing. Validating against a schema is a form of linting anyway.

**Comment by jonathanewerner** [comment]
I wonder though if it should be possible to opt-out of rules (like eslintrc allows it) or if that's overkill. @kentcdodds thoughts?

**Comment by bebraw** [comment]
@jonathanewerner Yeah, strict mode probably has to be opt-in. Just having a flag would be a starting point. Then go more granular when necessary.

**Comment by bebraw** [comment]
One more thought. If you want granularity straight from start, you could consider Babel style monorepo. Push individual checks below the main repo so that each is a package of its own. Then have a strict preset and a plugin loading mechanism. Maybe overkill, but still.

**Comment by jonathanewerner** [comment]
I think "strict mode" has been implemented via rules that are opt-in. What do you think, @bebraw ?

**Comment by bebraw** [comment]
opt-in would work, yeah.

**Comment by jonathanewerner** [comment]
:+1: Will close this then.
