### ISSUE TITLE
Strict mode - Disallow duplicate keys in object configuration

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#40]
We probably can't detect this at webpack-validator. ESLint can detect this, though. Common gotcha so opening anyway.

**Comment by jonathanewerner** [comment]
I think joi does this by default? Have to double check..

**Comment by jonathanewerner** [comment]
Yea, Joi doesn't validate against it. I'd think this would be eslint [`no-dupe-keys`](http://eslint.org/docs/rules/no-dupe-keys) job, no?

**Comment by bebraw** [comment]
That's enough. Time to close this?

**Comment by kentcdodds** [comment]
>  I'd think this would be eslint no-dupe-keys job, no?

I agree. Though, I think we need to make a decision about the scope of this project. Are we going to be "ok" with leaving some things up to ESLint, or should we assume that we'll do everything a developer needs to validate their config?

**Comment by jonathanewerner** [comment]
I'd prefer a narrower scope in favor of unix philosophy, ie "do one thing very well".
