### ISSUE TITLE
Chore: change version requirement for passing-config deps to *

### ISSUE THREAD

**Issue by jonathanewerner** [js-dxtools/webpack-validator#51]
### :octocat: Starter issue  
We would like to take the opportunity to invite someone who did not yet contribute to webpack-validator to work on this issue. Follow @YourFirstPR on Twitter for more of these issues across many open source projects :)

#### :bug: The Problem
In order to trigger greenkeeper less often, it'd be nice to have all versions for dependencies that are required *only* from the files in the folder `test/passing-configs` wild carded (set to `*` in package.json). 

Steps:
- [ ] Claim this issue
- [ ] Follow setup instructions in [CONTRIBUTING.md](https://github.com/jonathanewerner/webpack-validator/blob/master/CONTRIBUTING.md). [This course](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) might also be helpful to answer some questions that might arise. :)
- [ ] look for requires in `test/passing-configs` that only occur here, not in the rest of the code base. An example would be `copy-webpack-plugin`. Change the version for those dependencies to `*` in the `package.json`. 
- [ ] Commit und push changes to your branch. It doesn't have to be perfect, if tests don't pass, use the git flag `--no-verify` on your `git commit` and push to ask for help. 
- [ ]  You are done :clap:. Comment below that your pull request is ready for review.

**Comment by nlarche** [comment]
I'd like to help out with this issue.

**Comment by nlarche** [comment]
Pull request #74 is ready for review
