### ISSUE TITLE
Add option not to print on success?

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#69]
Printing `[webpack-validator] Config is valid.` on success isn't good if you are using webpack's `--json` option with webpack-validator as that leads to broken output.

Do you think it would make sense to add some sort of option to disable printing on success? How would you handle this?

Related: https://github.com/survivejs/webpack/issues/79

**Comment by nyrosmith** [comment]
What about calling the option "quietSuccess"?
Would be more explicit than just quiet

**Comment by jonathanewerner** [comment]
I think `quiet` is a pretty much standardized option name for muting normal logs, but not error logs. If we add a nice explanation in the README I think it'll be perfectly fine. 👍🏻
