### ISSUE TITLE
Strict mode - Never include anything from standard Node?

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#76]
This can bloat a bundle surprisingly so it would be good to at least warn against this. It's easy to end up in a situation where a dependency of a dependency brings some heavy Node part to your bundle.

**Comment by jonathanewerner** [comment]
How should this be inferred from the config?

**Comment by bebraw** [comment]
It cannot be inferred trivially. That's the problem. There would have to be something that's able to peek at webpack stat output.

**Comment by jonathanewerner** [comment]
Sounds like a tangential, new project, but not like webpack-validator, which only analyzes config, don't you think?
It'd be interesting though, could be called "webpack-bundle-analyzer", analyzing result bundle by looking at stats.

**Comment by bebraw** [comment]
Yup. A separate project would be fine. Just wanted to dump this somewhere. 👍

**Comment by bebraw** [comment]
Related project btw, https://github.com/robertknight/webpack-bundle-size-analyzer .

**Comment by jonathanewerner** [comment]
I've used https://github.com/robertknight/webpack-bundle-size-analyzer in the past to analyze bundle size. Would this already be of help for the given problem?

Edit: ok you just posted it. :D

**Comment by bebraw** [comment]
Yeah, I was just thinking it would make sense to discuss with that guy.

**Comment by jonathanewerner** [comment]
So we can probably close this here, right?

**Comment by bebraw** [comment]
Yeah. Let's close this one.
