### ISSUE TITLE
Strict mode - Disallow `resolve.root`

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#77]
Even though `resolve.root` can make for short imports, it can also cause strange issues due to aliasing. If you happen to have a directory matching to a npm dependency name, you might end up picking up the directory over the npm dependency. This can be hard to debug. This should yield a warning at least.

**Comment by jonathanewerner** [comment]
:) we use this extensively at my job and it's quite essential. Your point is of course valid. I'm not sure that I'd like to lint against this, as the benefits are huge. :)

**Comment by kentcdodds** [comment]
I think it'd be great to earn against using an alias that matches a dependency name though!

**Comment by bebraw** [comment]
> I think it'd be great to warn against using an alias that matches a dependency name though!

That would be enough I think. Disallowing whole field would be too much. This would solve the problem.

**Comment by jonathanewerner** [comment]
So let's maybe close this and reopen as "Warn for aliases that match a dependency name"?

**Comment by bebraw** [comment]
Done.
