### ISSUE TITLE
Strict mode - Warn for aliases that match a dependency name

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#79]
This should check for `resolve.root` at least. The point is that we want to avoid a case where webpack picks up something from the project root over `node_modules`.

Related: https://github.com/reactjs/redux/issues/1681 .

**Comment by jonathanewerner** [comment]
Implementation approach: the `_.intersection` of the a) array of folder names in node_modules with the b) flattened array of subfolders under all `resolve.root` folders should be empty.

**Comment by jonathanewerner** [comment]
I am on this, using joi 9 `.extend` and it's awesome. :) will probably pr tomorrow.

**Comment by jonathanewerner** [comment]
A baseline version of this is implemented in #81.
