### ISSUE TITLE
Provide info on how to fix `Module build failed: Unrecognised input`

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#84]
This is the classic "loader doesn't match input" case. Webpack spews out `Module build failed: Unrecognised input` then.

Providing better information on how to fix this might go beyond the scope of webpack-validator, but I want to have the idea somewhere. The problem is that this is a check relying on Webpack output. If I remember right, stats might have this information on error. Perhaps a stats related tool would be the right place for this.

The issue comes up particularly with newbies so it would be cool to provide something little better here.

**Comment by jonathanewerner** [comment]
What about creating a new project called "webpack-build-analyzer" or "webpack-analyzer" that analyzses stats/errors ? This would allow a clear separation of concerns. webpack-validator just looks at config, analyzer looks at stuff after build.

**Comment by jonathanewerner** [comment]
So webpack-build-size-analyzer is taken, webpack-analyzer has a package on npm as well, but seems quite unmaintained. mmh.

**Comment by jonathanewerner** [comment]
I [created a repo](https://github.com/js-dxtools/webpack-build-analyzer) to collect these ideas. Name can be bike-shedded about, this is just to get this started.

**Comment by bebraw** [comment]
Cool. Thanks.
