### ISSUE TITLE
output.publicPath validation is too strict

### ISSUE THREAD

**Issue by bebraw** [js-dxtools/webpack-validator#88]
The following should pass:

```javascript
output: {
 ...
 publicPath: ''
}
```

The current check is too strict. We might need `Joi.alternative` there to allow for empty given it's valid configuration. I use that as a placeholder.

Do you want a PR for this?

**Comment by jonathanewerner** [comment]
Yep. lets allow empty string. I think my implementation was meant as a best practice but I don't fully remember why it's supposed to be a best practice haha.
